### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by momoai96** [paulgavrikov/visualkeras#24] opened 2022-01-25 12:29 UTC
Hey,

I'm using a quite complex functional model and want to show it with your beautiful package. 
I know it's not fully supported, but I got a really strange error.
By using:

`font = ImageFont.truetype("/Library/fonts/Arial.ttf", fontsize)
visualkeras.layered_view(model_test).show()`

I receive:
`    z = min(max(z), max_z)
TypeError: 'int' object is not iterable`

My toyexample on Mnist works, so I don't know what to do

Help is appreciated :)

**Comment by momoai96** [comment] 2022-01-25 12:39
Hey Guys,

directly installing master branch solves it!

This is such an amazing tool!

**Comment by paulgavrikov** [comment] 2022-01-26 12:17
Thanks for the kind words! This is a duplicate of #15, so I will close this here.

**Closed by paulgavrikov** 2022-01-26 12:17 UTC
Labels: bug, duplicate
