### ISSUE TITLE
Cov1D model visualization 

### ISSUE THREAD

**Issue by Mahsa000** [paulgavrikov/visualkeras#31] opened 2023-02-03 19:15 UTC
Hi, 
I am receiving the following error when I am trying to use your library to visualize my Conv1D model. How can I still use it? Thanks.
```
TypeError                                 Traceback (most recent call last)
Cell In [54], line 2
      1 import visualkeras
----> 2 visualkeras.layered_view(model)

File /opt/miniconda3/envs/tensorflow/lib/python3.9/site-packages/visualkeras/layered.py:100, in layered_view(model, to_file, min_z, min_xy, max_z, max_xy, scale_z, scale_xy, type_ignore, index_ignore, color_map, one_dim_orientation, background_fill, draw_volume, padding, spacing, draw_funnel, shade_step, legend, font, font_color)
     98     x = min(max(shape[1] * scale_xy, x), max_xy)
     99     y = min(max(shape[2] * scale_xy, y), max_xy)
--> 100     z = min(max(z), max_z)
    101 elif len(shape) == 2:
    102     if one_dim_orientation == 'x':

TypeError: 'int' object is not iterable

```

**Comment by paulgavrikov** [comment] 2023-02-19 16:42
This is a duplicate of https://github.com/paulgavrikov/visualkeras/issues/15.

**Closed by paulgavrikov** 2023-02-19 16:42 UTC
