### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EmanRaslan88** [paulgavrikov/visualkeras#17] opened 2021-11-12 04:55 UTC
I tried to visualize 1D CNN model but not works

               TypeError: 'int' object is not iterable

![image](https://user-images.githubusercontent.com/45012873/141411943-1aee05d6-9095-4aac-a34a-9a21f210e27d.png)

**Comment by paulgavrikov** [comment] 2021-11-15 11:30
This is a duplicate of #15. Please check the solution there.

**Closed by paulgavrikov** 2021-11-15 11:30 UTC
Labels: bug, duplicate
